# this is manifest file for client that is React(vite)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-dep
  namespace: project-namespace
  labels:
    app: clientd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testclient 
  template:
    metadata:
      labels:
        app: testclient
    spec:
      containers:
        - name: client-cont
          image: shudhodhan/nodeappclient:33
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"          
          livenessProbe:
            tcpSocket:
              port: 80  # This is for node later if changed the image to nginx make it 80
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 4
            failureThreshold: 2
          readinessProbe:
            tcpSocket:
              port: 80  # This is for node later if changed the image to nginx make it 80
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 4
            failureThreshold: 2
          ports:
            - containerPort: 5173

---

apiVersion: v1
kind: Service
metadata:
  name: client-svc
  namespace: project-namespace
  labels:
    app: clients
spec:
  type: NodePort
  selector:
    app: testclient
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30007
