# this is an persistent volume creation
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume-pv
  labels:
    app: pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
